<a href="https://colab.research.google.com/github/shimulsarker10/Data-Analytics-Journey/blob/main/month-1-foundations/Data_Handling_Libraries/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
# Create a Numpy Array by passing tuple
n = np.array((1,2,3,4))
print(n)
print(type(n))

[1 2 3 4]
<class 'numpy.ndarray'>


In [3]:
# Create a Numpy Array by passing list
x = np.array([5,6,7,8])
print(x)
print(type(x))

[5 6 7 8]
<class 'numpy.ndarray'>


In [4]:
# Dimensions in arrays
# 0-D Array
x = np.array(4)
print(x)
print("Dimension:",x.ndim)

4
Dimension: 0


In [5]:
# 1-D Array
x = np.array([1,2,3,4])
print(x)
print("Dimension:",x.ndim)

[1 2 3 4]
Dimension: 1


In [6]:
# 2-D Array
x = np.array([[1,2,3],[4,5,6]])
print(x)
print("Dimension:",x.ndim)

[[1 2 3]
 [4 5 6]]
Dimension: 2


In [7]:
# Create a 3-D array with 2-d arrays
x=np.array([[[1,2,3],[3,4,5]],[[6,7,8],[9,10,11]]])
print(x)
print("Dimension:",x.ndim)

[[[ 1  2  3]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
Dimension: 3


In [8]:
# Initialize numpy arrays
x = np.zeros([3,3])
print(x)
print(type(x))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
<class 'numpy.ndarray'>


In [9]:
# Higher Dimensional array
x = np.array([1,2,3,4],ndmin=5)
print(x)
print("Dimension:",x.ndim)

[[[[[1 2 3 4]]]]]
Dimension: 5


In [10]:
arr = np.array([1,2,3,4,5])
print(arr[0])
print(arr[1])
print(arr[2] + arr[3])

1
2
7


In [11]:
# Numpy Array Indexing
x = np.array([1,2,3,4,5])
for n in(range(len(x))):
    print(x[n])

1
2
3
4
5


In [12]:
# Access 2-D Array
x = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(x[1,2])

8


In [13]:
# access 3-d array
x = np.array([[[11,45,23,],[35,90,50]],[[30,40,95],[10,20,30]]])
print(x[1,1,2])

30


In [14]:
#numpy array slicing
x = np.array([1,2,3,4,5,])
print(x[1:4])

[2 3 4]


In [15]:
# Use the step value to determine the step of the slicing
x = np.array([1,2,3,4,5,6,])
print(x[1:5:2])

[2 4]


In [16]:
# Slicing 2D array
n = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(n[1,1:4])

[7 8 9]


In [17]:
#check the size ,shape and dtype
x = np.array([1,2,3,4,5])
print(x.size)
print(x.shape)
print(x.ndim)

5
(5,)
1


In [18]:
#Special Array
n=np.zeros([2,3])
m=np.ones([3,3])
k=np.eye(3)
l=np.arange(0,10,2)
r=np.linspace(0,1,5)
print(n.size,n.shape,n.ndim)
print(m.size,m.shape,m.ndim)
print(k.size,k.shape,k.ndim)
print(l.size,l.shape,l.ndim)
print(r.size,r.shape,r.ndim)

6 (2, 3) 2
9 (3, 3) 2
9 (3, 3) 2
5 (5,) 1
5 (5,) 1


In [19]:
#Array "Reshape"
arr = np.array([1,2,3,4,5,6,7,8,9])
newarr = arr.reshape(3,3)
print(newarr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [20]:
# Vectorized Operations
x = np.array([1,2,3,4,5])
y = np.array([3,4,6,3,7])
print(x+y)
print(x-y)
print(x*y)
print(x/y)
print(x%y)

[ 4  6  9  7 12]
[-2 -2 -3  1 -2]
[ 3  8 18 12 35]
[0.33333333 0.5        0.5        1.33333333 0.71428571]
[1 2 3 1 5]


In [21]:
# Broadcasting
arr1 = np.array([3,5,6,7])
arr2 = np.array([4])
print (arr1 + arr2)

[ 7  9 10 11]


In [22]:
a = np.array([[3,7,9],[4,8,3]])
b = np.array([5,9,2])
print(a+b)

[[ 8 16 11]
 [ 9 17  5]]


In [23]:
# Useful functions
x = np.array([45,98,300,56,45])
print(np.max(x))
print(np.min(x))
print(np.sum(x))
print(np.mean(x))
print(np.std(x))

300
45
544
108.8
97.57335701921913


In [24]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])
d = np.array([4,7])
e = np.array([5,20,11,67])

result = np.concatenate((a,b,c))
print(result)

stack = np.stack((a,b,c))
print(stack)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [25]:
# Linear Algebra
a = np.array([[1,2],[4,5]])
b = np.array([[5,6],[7,8]])

# Matrix multiplication
print(np.dot(a,b))
print(a @ b) #shortcut

[[19 22]
 [55 64]]
[[19 22]
 [55 64]]


In [26]:
# Transpose
x = np.array([[23,98,39],[34,55,80]])
print(x.T)

[[23 34]
 [98 55]
 [39 80]]


In [27]:
# Determinant
n = np.array([[1, 2], [3, 4]])

print(np.linalg.det(n))

-2.0000000000000004


In [28]:
# Eigenvalues and Eigenvectors
x = np.array([[1, 2], [3, 4]])
values, vectors = np.linalg.eig(x)
print("Eigenvalues:",values)
print("Eigenvectors:",vectors)

Eigenvalues: [-0.37228132  5.37228132]
Eigenvectors: [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [29]:
# Exercise
A = np.array([[2,3],[1,4]])
B = np.array([[5,2],[3,1]])

print("A + B =\n", A + B)
print("A dot B =\n", np.dot(A,B))
print("Transpose of A =\n", A.T)
print("Inverse of A =\n", np.linalg.inv(A))
print("Determinant of A =", np.linalg.det(A))

A + B =
 [[7 5]
 [4 5]]
A dot B =
 [[19  7]
 [17  6]]
Transpose of A =
 [[2 1]
 [3 4]]
Inverse of A =
 [[ 0.8 -0.6]
 [-0.2  0.4]]
Determinant of A = 5.000000000000001
